services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sysscore-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SysScore_2026!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
