// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SysScore.Data;

#nullable disable

namespace SysScore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613201212_AddThreatDetectionMetrics")]
    partial class AddThreatDetectionMetrics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SysScore.Models.SystemData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BootTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("CpuUsage")
                        .HasColumnType("float");

                    b.Property<double>("DiskFreeGb")
                        .HasColumnType("float");

                    b.Property<double>("DiskUsage")
                        .HasColumnType("float");

                    b.Property<int>("EstablishedConnectionCount")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("HighCpuProcessCount")
                        .HasColumnType("int");

                    b.Property<int>("HighMemoryProcessCount")
                        .HasColumnType("int");

                    b.Property<double>("InboundPacketRate")
                        .HasColumnType("float");

                    b.Property<string>("LargestUnnecessaryFiles")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ListeningPortCount")
                        .HasColumnType("int");

                    b.Property<int>("NetworkConnectionCount")
                        .HasColumnType("int");

                    b.Property<int>("NetworkConnectionDelta")
                        .HasColumnType("int");

                    b.Property<double>("OutboundPacketRate")
                        .HasColumnType("float");

                    b.Property<int>("ProcessCount")
                        .HasColumnType("int");

                    b.Property<double>("RamUsage")
                        .HasColumnType("float");

                    b.Property<string>("RecommendedActions")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<int>("SecurityScore")
                        .HasColumnType("int");

                    b.Property<double>("SwapUsage")
                        .HasColumnType("float");

                    b.Property<int>("SynSentConnectionCount")
                        .HasColumnType("int");

                    b.Property<long>("SystemUptimeSeconds")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ThreatDetectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThreatEvidence")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("ThreatLevel")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ThreatScore")
                        .HasColumnType("int");

                    b.Property<string>("ThreatType")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("TimeWaitConnectionCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UniqueRemoteAddressCount")
                        .HasColumnType("int");

                    b.Property<int>("UniqueRemotePortCount")
                        .HasColumnType("int");

                    b.Property<int>("UnnecessaryFileCount")
                        .HasColumnType("int");

                    b.Property<string>("UnnecessaryFileLocations")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("UnnecessaryFileSizeMb")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("SystemDataRecords", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
